
if ENV['INSTITUTION_NAME']
  INSTITUTION_NAME =  ENV['INSTITUTION_NAME']
else
  INSTITUTION_NAME =  'NA'
end 


if ENV['WKHTMLTOPDF']
  WKHTMLTOPDF =  ENV['WKHTMLTOPDF']
else
  WKHTMLTOPDF =  'wkhtmltopdf'
end 

if ENV['NUM_WORKERS']
NUM_WORKERS = ENV['NUM_WORKERS'].to_i
else
NUM_WORKERS = 4
end